spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT
    username: root
    password: 123456
  # redis 配置
  redis:
    host: localhost
    post: 6379

# Mybatis 配置
mybatis:
  type-aliases-package: com.cimo.domain
  mapper-locations: classpath:mapper/*Mapper.xml


